# TODO: currently disabled in settings
name: 🚀 Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    if: ${{ !github.event.act }} # skip during local actions testing

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 🐍
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install Hatch 🐣
      run: pip install --upgrade pip setuptools wheel twine "hatch==1.7.0"

    - name: Build 🔨
      run: hatch build

    - name: 🚀 Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
